name: Deploy_ChatQnA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Environment Variables
        run: |
          echo "HOST_IP=${{ secrets.HOST_IP }}" >> $GITHUB_ENV
          echo "NO_PROXY=${{ secrets.NO_PROXY }}" >> $GITHUB_ENV
          echo "HUGGINGFACEHUB_API_TOKEN=${{ secrets.HUGGINGFACEHUB_API_TOKEN }}" >> $GITHUB_ENV

      - name: Run ChatQnA Setup Script
        run: |
          cd docsum/docker_compose/
          source ./set_env.sh

      - name: Start Docker Compose
        run: |
          cd docsum/docker_compose/intel/cpu/xeon/
          docker compose up -d

      - name: Verify Deployment
        run: |
          sleep 30
          curl -X POST "http://${{ env.HOST_IP }}:8888/v1/chatqna" \
            -H "Content-Type: application/json" \
            -d '{"messages": "Test deployment success?"}'

      - name: Check Logs (If Deployment Fails)
        if: failure()
        run: |
          docker logs chatqna-xeon-backend-server
